@startuml ユースケース図

left to right direction

actor ユーザー #yellow

skinparam Monochrome false

package "GameBargain" #fafad2 {
    usecase 価格を比較する #ffd700
    usecase ゲームを探す #ffd700
        usecase ゲーム名で絞り込む #ffd700
        usecase 価格別で絞り込む #ffd700
        usecase 評価別で絞り込む #ffd700
        usecase 割引率で絞り込む #ffd700
    usecase ゲームの価格を確認する #ffd700
    usecase セール情報を確認する #ffd700
    usecase 外部サイトへ遷移する #ffd700
}



ユーザー --> 価格を比較する
    価格を比較する --> 価格別で絞り込む
ユーザー --> ゲームを探す

    ゲームを探す --> ゲーム名で絞り込む
    ゲームを探す --> 評価別で絞り込む
    ゲームを探す --> 割引率で絞り込む

ユーザー --> ゲームの価格を確認する
ユーザー --> セール情報を確認する
ユーザー --> 外部サイトへ遷移する




@enduml