"""Add platforms field to Game model

Revision ID: 4b61c512c1d8
Revises: 8074bb9ed627
Create Date: 2025-07-18 00:23:42.575503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b61c512c1d8'
down_revision = '8074bb9ed627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platforms', sa.Text(), nullable=True, comment='対応プラットフォーム（カンマ区切り）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('platforms')

    # ### end Alembic commands ###
