"""empty message

Revision ID: 8074bb9ed627
Revises: 
Create Date: 2025-07-16 17:34:33.144905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8074bb9ed627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_url', sa.String(length=500), nullable=True, comment='Steam商品ページURL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('steam_url')

    # ### end Alembic commands ###
